### ISSUE TITLE
Create a Technical / Performance Rider

### ISSUE THREAD

**Issue by crgrafton** [bawdycaste/bawdycaste.com#55]
We need to create a rider to provide venues when they say "what do you need to do the show?"

We know we need things like:  
- a place to change
- some power
- a place to eliminate human waste
- ? ? ? 
- profit?

**Comment by ninaloschiavo** [comment]
As far as preshows, I don’t know that there is anything the venue would provide that the MC or cast would not... Would it help for me to brainstorm other department’s needs as well?

**Comment by xtoferprime** [comment]
> As far as preshows, I don’t know that there is anything the venue would provide that the MC or cast would not... Would it help for me to brainstorm other department’s needs as well?

@ninaloschiavo heck yeah!

**Comment by xtoferprime** [comment]
@dianerinella mentioned this [PaulRevereRider2010.pdf](https://github.com/bawdycaste/bawdycaste.com/files/3070945/PaulRevereRider2010.pdf) as a resource to look at, there were a few other examples too but now I'm having trouble finding them.
